#In OAuth, clients are the applications that use an external OAuth service
[[clients]]
id = "dcpm"
secret = "WhateverSecretYouWant"
redirectUri = "https://localhost:1543/callback"
scopes = ["client_based_scopes_here"]

[[clients]]
id = "ovs"
secret = "WhateverSecretYouWant"
redirectUri = "https://localhost:1543/callback"
