[users]
[users.rob]
email = "rob@incubaid.com"
name = "Rob Van Mieghem"
[users.rob.password]
key = "4SUhWjwcZ6RNK1GQbQr4hWfPeC6QeFBRW89QxSXQLDRwkZjYMhA7QSh4tVH6k7xeNEUfSqLyUhp55VoFty6SzTsy"
salt = "NCLWiefARemEmmycvWCGVq"

[users.kds]
email = "kristof@indubaid.com"
name = "kristof De Spiegeleer"
[users.kds.password]
key = "4N2v4UxbatBMAcMPMT8aeskjqw3ZuMZBvP325qHAFLTUGey6zWZ1QNkSsBX5PZP49b17c9sVPDAHPVpqfF7WXA1f"
salt = "EzdUkeoVqmm83zKwFMihsv"
