[users]
[users.rob]
email = "rob@incubaid.com"
name = "Rob Van Mieghem"
scopes = [ "ovs" , "dcpm"]
[users.rob.password]
key = "4SUhWjwcZ6RNK1GQbQr4hWfPeC6QeFBRW89QxSXQLDRwkZjYMhA7QSh4tVH6k7xeNEUfSqLyUhp55VoFty6SzTsy"
salt = "NCLWiefARemEmmycvWCGVq"

[users.kds]
email = "kristof@indubaid.com"
name = "kristof De Spiegeleer"
scopes = [ "ovs" , "dcpm"]
[users.kds.password]
key = "4N2v4UxbatBMAcMPMT8aeskjqw3ZuMZBvP325qHAFLTUGey6zWZ1QNkSsBX5PZP49b17c9sVPDAHPVpqfF7WXA1f"
salt = "EzdUkeoVqmm83zKwFMihsv"

[users.henri]
email = "henriverroken@gmail.com"
name = "Henri Verroken"
scopes = [
    "request_available",
    "lenoir2",
    "bracknell1",
    "york1",
    "dco1",
]

[users.henri.password]
key = "3QZUFNzhQZ6khdfFbM4tfYt2VHqNJt6gFzfezfoKZHmm3MJ3pt8cCMQLZvwQAxowq8wPmDas6pUUYEkaLBwhSjuL"
salt = "DpU9KdDWbeix8GXFcNwqp"
