#!/bin/bash
set -e
source "$(dirname $(readlink -f $0))/_functions"

cp /etc/hosts /etc/hosts.bak
umount /etc/hosts || true
cp /etc/hosts.bak /etc/hosts
installovsrepo
apt-get install -y iproute2 net-tools rsyslog sudo udev

red="/etc/systemd/system/redis-server.service.d/"
mkdir -p $red
echo '[Service]' > $red/redis.override.conf
echo 'PrivateDevices=no' >> $red/redis.override.conf

apt-get install -y volumedriver-no-dedup-server
apt-get install -y openvstorage-hc
systemctl enable cron
systemctl start cron
IPSUFFIX=$(($(hostname -s | sed "s/[^0-9]//g") + 9))

cat << EOF > /opt/asd-manager/config/preconfig.json
{
    "asdmanager": {
        "api_ip": "172.17.1.$IPSUFFIX", 
        "asd_start_port": 8600, 
        "asd_ips": [
            "172.17.1.10"
        ], 
        "api_port": 8500
    }
}
EOF
cat << EOF > /opt/OpenvStorage/config/preconfig.json
{"setup": {                    
  "cluster_ip": "172.17.1.$IPSUFFIX", 
  "enable_heartbeats": true,   
  "external_config": null,     
  "logging_target": null,      
  "master_ip": "172.17.1.$IPSUFFIX",  
  "master_password": null,     
  "node_type": "master",       
  "rdma": false,               
  "rollback": null             
}}                             
EOF
ovs setup
jspython /opt/code/github/0-complexity/openvcloud_installer/scripts/install/installnode --role=storage --masterips 172.17.1.1 --password=rooter --gid=66 --fqdn=172.17.1.1 --gwmgmt_ip=10.199.0.14/22 --vxbackend_vlan=2313 --vxbackend_ip=10.240.0.14/16 --gwmgmt_vlan=2314 --env=devsetup --client_id=greenitglobe.development.environments.local --secret=7b6nPW0EpZ3XGAPPxrs3nV8g5119yLcAmoQGUqlXn8uT_hciAIZF --grid_id=66 --ovs_url=https://172.17.1.10
jspython /opt/code/github/0-complexity/openvcloud/scripts/ovs/alba-create-user.py
jspython /opt/code/github/0-complexity/openvcloud/scripts/dev/localnode/setupovs.py
echo "
portal_config = j.core.config.get('portal_client', 'main')
portal_config['port'] = 80
j.core.config.set('portal_client', 'main', portal_config)
"|js