class Machine(object):
    """
    Define possible machine model status
    """

    VIRTUAL = "VIRTUAL"
    DEPLOYING = "DEPLOYING"
    STOPPING = "STOPPING"
    STARTING = "STARTING"
    HALTED = "HALTED"

    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    RESTORING = "RESTORING"
    DELETED = "DELETED"
    DESTROYED = "DESTROYED"
    ERROR = "ERROR"

    PAUSING = "PAUSING"
    RESUMING = "RESUMING"
    REBOOTING = "REBOOTING"
    RESETING = "RESETING"
    DELETING = "DELETING"
    DESTROYING = "DESTROYING"
    ADDING_DISK = "ADDING_DISK"
    ATTACHING_DISK = "ATTACHING_DISK"
    DETACHING_DISK = "DETACHING_DISK"

    INVALID_STATES = [DESTROYED, DELETED, ERROR, DESTROYING]
    NON_CONSUMING_STATES = [DESTROYED, DELETED, ERROR, HALTED]
    TRANSITION_STATES = [DEPLOYING, STOPPING, STARTING, DELETING, DESTROYING, ADDING_DISK, ATTACHING_DISK, DETACHING_DISK]

    VALID_STATES = [PAUSED, HALTED, RUNNING]
    UP_STATES = [RUNNING, PAUSED]

    ALLOWED_TRANSITIONS = {
        VIRTUAL: [DEPLOYING],
        RUNNING: [PAUSING, STOPPING, DELETING, RESETING, REBOOTING, ADDING_DISK, ATTACHING_DISK, DETACHING_DISK],
        PAUSED: [RESUMING, STOPPING, DELETING, RESETING, REBOOTING, ADDING_DISK, ATTACHING_DISK, DETACHING_DISK],
        HALTED: [STARTING, DELETING],
        DELETED: [RESTORING, DESTROYING],
        DESTROYED: [],
        PAUSING: [PAUSED],
        STOPPING: [HALTED],
        DELETING: [DELETED],
        RESTORING: [HALTED],
        DESTROYING: [DESTROYED],
    }



class Cloudspace(object):
    # static states
    VIRTUAL = "VIRTUAL"
    DEPLOYED = "DEPLOYED"
    DESTROYED = "DESTROYED"
    DISABLED = "DISABLED"
    DELETED = "DELETED"

    # transition states
    DEPLOYING = "DEPLOYING"
    DISABLING = "DISABLING"
    ENABLING = "ENABLING"
    DELETING = "DELETING"
    DESTROYING = "DESTROYING"
    RESTORING = "RESTORING"

    TRANSITION_STATES = [DEPLOYING, DISABLING, ENABLING, DELETING, DESTROYING, RESTORING]
    INVALID_STATES = [DESTROYED, DELETED, DESTROYING, DELETING]
    ALLOWED_TRANSITIONS = {
        VIRTUAL: [DEPLOYING],
        DEPLOYED: [DISABLING, DELETING],
        DISABLED: [ENABLING, DELETING],
        DELETED: [DESTROYING, RESTORING],
        DESTROYED: [],
        DEPLOYING: [DEPLOYED],
        DISABLING: [DISABLED],
        ENABLING: [DEPLOYED],
        DELETING: [DELETED],
        DESTROYING: [DESTROYED],
    }

class Account(object):
    DESTROYED = "DESTROYED"
    DESTROYING = "DESTROYING"
    CONFIRMED = "CONFIRMED"
    DISABLED = "DISABLED"
    DELETED = "DELETED"
    INVALID_STATES = [DESTROYED, DESTROYING, DELETED]


class Disk(object):
    ASSIGNED = "ASSIGNED"
    MODELED = "MODELED"
    CREATING = "CREATING"
    CREATED = "CREATED"
    DESTROYED = "DESTROYED"
    DELETED = "DELETED"
    TOBEDELETED = "TOBEDELETED"
    INVALID_STATES = [DESTROYED, TOBEDELETED, DELETED]


class Image(object):
    CREATED = "CREATED"
    CREATING = "CREATING"
    DESTROYED = "DESTROYED"
    DELETED = "DELETED"
    DISABLED = "DISABLED"
    INVALID_STATES = [DESTROYED, DELETED]

